name: user
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  geolocator: ^10.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  like_button: ^2.0.8
  introduction_screen: ^3.1.8
  shared_preferences: ^2.2.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png